blizzard:
  time: 20
  duration: 5

temperature:
  max: 15
  maxWithBlizzard: 3
  initialTemperature: 10
  freezingTemperature: 0
  timeToDecay: 10
  temperatureDecay: 0.1
  damage: 1

clothes:
  common:
    percentage: 5
  rare:
    percentage: 15
  mystic:
    percentage: 25
  legendary:
    percentage: 35

schem:
  name: "core.schem"