monsters:

  max-level: 100

  initial-monsters-limit: 5

  hit-delay: 350 # in milliseconds

  command-whitelist:
    - "/spawn"
    - "/lobby"
    - "/l"
    - "/monstros"
    - "/monstros sair"
    - "/monstro"
    - "/monstro sair"
    - "/bosses"
    - "/bosses sair"
    - "/boss"
    - "/boss sair"
    - "/g"
    - "/l"
    - "/global"
    - "/local"