name: blizzard-currencies
version: '${version}'
main: blizzard.development.currencies.Main
api-version: '1.20'
depend: [Vault]
softdepend: [PlaceholderAPI]
commands:
  currencies:
  souls:
  flakes:
  fossils:
  limits: