name: blizzard-essentials
version: '${version}'
main: blizzard.development.essentials.Main
api-version: '1.20'
commands:
  essentials:
  gamemode:
  clearchat:
  clear:
  heal:
  trash:
  warp:
  setspawn:
  tpall:
  vanish:
  echest: