fishing:
  taskTime: 3

frozenFishChance: 50

fishes:
  bacalhau:
    rarity: "common"

  salmao:
    rarity: "common"

  caranguejo:
    rarity: "rare"

  lagosta:
    rarity: "rare"

  lula:
    rarity: "legendary"

  lula_brilhante:
    rarity: "legendary"

  tubarao:
    rarity: "mystic"

  baleia:
    rarity: "mystic"

level:
  initial: 100
  perLevel: 20
  multiplier: 1.5

strengthNeeded:
  common: 1
  rare: 2
  legendary: 3
  mystic: 4

valueByRarity:
  common: 1
  rare: 2
  legendary: 3
  mystic: 4
  frozen: 3

xpByRarity:
  common: 1
  rare: 2
  legendary: 3
  mystic: 4
  frozen: 3

unfreeze:
  value: 10

events:
  time: 20
  geyser:
    duration: 5

