fishes:
  bacalhau:
    rarity: "common"
    price: 1

  salmao:
    rarity: "common"
    price: 2

  caranguejo:
    rarity: "rare"
    price: 3

  lagosta:
    rarity: "rare"
    price: 4

  lula:
    rarity: "legendary"
    price: 5

  lula_brilhante:
    rarity: "legendary"
    price: 6

  tubarao:
    rarity: "mystic"
    price: 7

  baleia:
    rarity: "mystic"
    price: 8