fishes:
  bacalhau:
    rarity: "common"

  salmao:
    rarity: "common"

  caranguejo:
    rarity: "rare"

  lagosta:
    rarity: "rare"

  lula:
    rarity: "legendary"

  lula_brilhante:
    rarity: "legendary"

  tubarao:
    rarity: "mystic"

  baleia:
    rarity: "mystic"

strengthNeeded:
  common: 1
  rare: 2
  legendary: 3
  mystic: 4

valueByRarity:
  common: 1
  rare: 2
  legendary: 3
  mystic: 4

xpByRarity:
  common: 1
  rare: 2
  legendary: 3
  mystic: 4

